services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --db=dev-file
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - db

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8888:8080"

volumes:
  pgdata:
  keycloak_data:
